- name: Check for Muster binary
  stat:
    path: /usr/local/muster9/rc9.bin
  register: muster_bin

- name: Check Muster systemd service active
  command: systemctl is-active muster9rcd.service
  register: muster_service
  changed_when: false
  failed_when: false

- name: Set muster_installed fact
  set_fact:
    muster_installed: "{{ (muster_bin.stat.exists | default(false)) or (muster_service.rc == 0) }}"

- name: Skip notice if already installed
  debug:
    msg: "Muster already installed. Skipping copy/extract/install/ownership steps."
  when: muster_installed

- name: Copy Muster installer tarball
  when: not muster_installed
  copy:
    src: Muster9.0.14.11632.x64.linux.tar.gz
    dest: "/home/{{ muster_user }}/work/Muster9.0.14.11632.x64.linux.tar.gz"
    owner: "{{ muster_user }}"
    group: "{{ muster_user }}"
    mode: '0644'

- name: Extract tarball
  when: not muster_installed
  unarchive:
    src: "/home/{{ muster_user }}/work/Muster9.0.14.11632.x64.linux.tar.gz"
    dest: "/home/{{ muster_user }}/work/"
    remote_src: yes
    owner: "{{ muster_user }}"
    group: "{{ muster_user }}"
    creates: "/home/{{ muster_user }}/work/Muster9.0.14.x64.linux"

- name: Run installer
  when: not muster_installed
  become: true
  command: "./install -c -t -i {{ muster_dispatcher }}"
  args:
    chdir: "/home/{{ muster_user }}/work/Muster9.0.14.x64.linux"

- name: Ensure ownership of /usr/local/muster9
  when: not muster_installed
  file:
    path: /usr/local/muster9
    state: directory
    owner: "{{ muster_user }}"
    group: "{{ muster_user }}"
    recurse: yes

# 방화벽 설정(항상 멱등 적용)
- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: present

- name: Ensure firewalld service is running and enabled
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open TCP port 9885 in public zone (permanent and immediate)
  ansible.posix.firewalld:
    zone: public
    port: 9885/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Reload firewalld to apply permanent changes
  ansible.builtin.service:
    name: firewalld
    state: reloaded
