- name: Install NFS and CIFS utils
  package:
    name:
      - nfs-utils
      - cifs-utils
    state: present

- name: Create mount points (skip if already a mountpoint)
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ mounts }}"
  when: item.path not in (ansible_mounts | map(attribute='mount') | list | default([]))

- name: Ensure mounts present and mounted
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop: "{{ mounts }}"
