- name: Enforce autoconnect=true for the active ethernet connection
  block:
    - name: Get the name of the active, non-loopback device
      become: true
      command: nmcli -t --fields DEVICE connection show --active
      register: nm_active_devices_raw
      changed_when: false

    - name: Extract the primary active device name
      set_fact:
        active_device_name: "{{ (nm_active_devices_raw.stdout_lines | reject('match', '^lo$') | list | first) | default('') }}"
      changed_when: false

    - name: Skip if no active non-loopback device is found
      debug:
        msg: "No active, non-loopback network device found. Skipping."
      when: active_device_name == ""

    - name: Find the nmconnection file for the active device
      become: true
      shell: |
        grep -l -E "^interface-name={{ active_device_name }}$" /etc/NetworkManager/system-connections/*.nmconnection 2>/dev/null || true
      args:
        executable: /bin/bash
      register: file_match
      changed_when: false
      when: active_device_name != ""

    - name: Set path for the connection file to edit
      set_fact:
        conn_file_to_edit: "{{ file_match.stdout }}"
      when: file_match.stdout is defined and file_match.stdout != ""

    - name: Ensure autoconnect=true in the active connection file
      become: true
      ini_file:
        path: "{{ conn_file_to_edit }}"
        section: connection
        option: autoconnect
        value: 'true'
        no_extra_spaces: true
        backup: true
      register: ac_edit
      when: conn_file_to_edit is defined and conn_file_to_edit != ""

    - name: Restart NetworkManager if the profile changed
      become: true
      service:
        name: NetworkManager
        state: restarted
      when: ac_edit.changed
